// Фото статей: url, alt, credit (Wikimedia Commons, свободные лицензии CC BY-SA/CC0).
// Файл загружается и на главной (превью в карточках), и доступен в Node (generate_articles.js).
const IMAGES = {
    1: { url: "/images/art-01.jpg", alt: "Электромобили в 2026 году: гонка за запасом хода в 1000 км", credit: "CEphoto, Uwe Aranas, CC BY-SA 3.0 (Wikimedia Commons)" },
    2: { url: "/images/art-02.jpg", alt: "Премьеры года: главные авто, которые выйдут на рынок", credit: "Фото: АвтоТема" },
    3: { url: "/images/art-03.jpg", alt: "Toyota: путь от ткацкого станка до мирового лидера", credit: "Фото: АвтоТема" },
    4: { url: "/images/art-04.jpg", alt: "Бензин, дизель, гибрид или электро: что выбрать в 2026?", credit: "Ferdinand Reus, CC BY-SA 2.0 (Wikimedia Commons)" },
    5: { url: "/images/art-05.jpg", alt: "Автопром будущего: беспилотники, каршеринг и новые рынки", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    6: { url: "/images/art-06.jpg", alt: "Зарядные станции: где заряжаться в дороге и сколько это стоит", credit: "Julian Herzog (Website), CC BY 4.0 (Wikimedia Commons)" },
    7: { url: "/images/art-07.jpg", alt: "Кроссоверы 2026: что выбирают семьи", credit: "Corvettec6r, CC0 (Wikimedia Commons)" },
    8: { url: "/images/art-08.jpg", alt: "Турбо или атмосферник: что надёжнее на самом деле", credit: "Quentin Schwinn (NASA), Public domain (Wikimedia Commons)" },
    9: { url: "/images/ferrari.jpg", alt: "Ferrari 250 GTO — легендарная модель марки", credit: "Фото: Lothar Spurzem, CC BY-SA 2.0 (Wikimedia Commons)" },
    10: { url: "/images/art-10.jpg", alt: "Tesla vs китайские бренды: кто лидирует в электромобилях", credit: "Alexander-93, CC BY-SA 4.0 (Wikimedia Commons)" },
    11: { url: "/images/art-11.jpg", alt: "Экологические нормы: как автопром готовится к запрету ДВС", credit: "Ruben de Rijcke, CC BY-SA 3.0 (Wikimedia Commons)" },
    12: { url: "/images/art-12.jpg", alt: "Volkswagen: «народный автомобиль» и его наследие", credit: "Фото: АвтоТема" },
    13: { url: "/images/art-13.jpg", alt: "Гибриды против электричества: считаем, что выгоднее", credit: "Alexander-93, CC BY-SA 4.0 (Wikimedia Commons)" },
    14: { url: "/images/art-14.jpg", alt: "Дизель жив? Что происходит с дизельными моторами", credit: "Lemon3 at German Wikipedia, CC BY-SA 3.0 (Wikimedia Commons)" },
    15: { url: "/images/art-15.jpg", alt: "Батареи будущего: натрий, твёрдый электролит и LFP", credit: "Raimond Spekking, CC BY-SA 4.0 (Wikimedia Commons)" },
    16: { url: "/images/porsche-911.jpg", alt: "Porsche 911 GT3 (992)", credit: "Фото: Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    17: { url: "/images/art-17.jpg", alt: "Китайские бренды штурмуют рынок: HAVAL, EXEED и Geely в лидерах", credit: "Jengtingchen, CC BY-SA 4.0 (Wikimedia Commons)" },
    18: { url: "/images/art-18.jpg", alt: "Гибриды 2026: больше не «переходный этап», а самостоятельный класс", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    19: { url: "/images/art-19.jpg", alt: "Быстрая зарядка важнее запаса хода: эпоха 800V и 900V", credit: "original: Michael Movchinedited by Felix Müller, CC BY-SA 3.0 (Wikimedia Commons)" },
    20: { url: "/images/art-20.jpg", alt: "Твёрдотельные батареи: прототип Mercedes проехал 1205 км", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    21: { url: "/images/art-21.jpg", alt: "Li Auto: электронное шасси и запас хода до 1650 км", credit: "Evnerd, CC BY-SA 4.0 (Wikimedia Commons)" },
    22: { url: "/images/art-22.jpg", alt: "Надёжность китайских машин: почему сервисы загружены на 51%", credit: "Alexander-93, CC BY-SA 4.0 (Wikimedia Commons)" },
    23: { url: "/images/art-23.jpg", alt: "Рейтинг продаж в Китае: Geely EX2, Xiaomi SU7 и гонка BYD", credit: "John kwame westafrica, CC0 (Wikimedia Commons)" },
    24: { url: "/images/art-24.jpg", alt: "ESTEO V27: гибрид на 456 л.с. за 5,75 млн рублей", credit: "JustAnotherCarDesigner, CC BY-SA 4.0 (Wikimedia Commons)" },
    25: { url: "/images/art-25.jpg", alt: "Zeekr, BMW и гонка за 900-вольтовые платформы", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    26: { url: "/images/art-26.jpg", alt: "Changan CS75 Plus AWD: локализация и полный привод", credit: "Jengtingchen, CC BY-SA 4.0 (Wikimedia Commons)" },
    27: { url: "/images/art-27.jpg", alt: "Xiaomi SU7: как телефонный гигант ворвался в автопром", credit: "Zoerides, CC0 (Wikimedia Commons)" },
    28: { url: "/images/art-28.jpg", alt: "Электромобиль зимой: теряем ли мы запас хода в мороз", credit: "John S Turner, CC BY-SA 2.0 (Wikimedia Commons)" },
    29: { url: "/images/art-29.jpg", alt: "LFP против тройного лития: какая батарея живёт дольше", credit: "Krzysztof Woźnica - KyloDee, Public domain (Wikimedia Commons)" },
    30: { url: "/images/art-30.jpg", alt: "Режим одной педали: что такое рекуперация и как ей пользоваться", credit: "Keanu4, CC BY-SA 3.0 (Wikimedia Commons)" },
    31: { url: "/images/art-31.jpg", alt: "Б/у электромобиль: на что смотреть при покупке", credit: " Dmitry Ivanov.., CC BY-SA 4.0 (Wikimedia Commons)" },
    32: { url: "/images/art-32.jpg", alt: "Спорткары 2026: электрические и гибридные бестселлеры", credit: "Matti Blume, CC BY-SA 4.0 (Wikimedia Commons)" },
    33: { url: "/images/art-33.jpg", alt: "Минивэны и семейные кроссоверы: обзор для больших семей", credit: "IFCAR, Public domain (Wikimedia Commons)" },
    34: { url: "/images/art-34.jpg", alt: "Бюджетные авто 2026: что купить до 2 млн рублей", credit: "JanekJankowski, CC BY-SA 4.0 (Wikimedia Commons)" },
    35: { url: "/images/art-35.jpg", alt: "Пикапы наступают: почему грузовые машины становятся модными", credit: "Sylvainbrousseau, CC BY-SA 3.0 (Wikimedia Commons)" },
    36: { url: "/images/art-36.jpg", alt: "Ремень ГРМ против цепи: что надёжнее и что дешевле", credit: "Criveros0248, CC BY-SA 3.0 (Wikimedia Commons)" },
    37: { url: "/images/art-37.jpg", alt: "Какое масло лить в двигатель и когда менять", credit: "Pittigrilli, CC0 (Wikimedia Commons)" },
    38: { url: "/images/art-38.jpg", alt: "Вариатор или АКПП: сравниваем коробки передач", credit: "Hoikka1, CC BY-SA 3.0 (Wikimedia Commons)" },
    39: { url: "/images/art-39.jpg", alt: "Как экономить топливо: 10 привычек водителя", credit: "Sonett72 at English Wikipedia, Public domain (Wikimedia Commons)" },
    40: { url: "/images/art-40.jpg", alt: "Робот против автомата: где подвох в «роботах»", credit: "Robbie Sproule from Montreal, Canada, CC BY 2.0 (Wikimedia Commons)" },
    41: { url: "/images/art-41.jpg", alt: "BMW: от авиационных двигателей до «тройки»", credit: "Jeroen Coebergh, CC0 (Wikimedia Commons)" },
    42: { url: "/images/art-42.jpg", alt: "Mercedes-Benz: рождение трёхлучевой звезды", credit: "Dietmar Rabich, CC BY-SA 4.0 (Wikimedia Commons)" },
    43: { url: "/images/art-43.jpg", alt: "Honda: от мопедов до легендарного NSX", credit: "ed g2s • talk, CC BY-SA 3.0 (Wikimedia Commons)" },
    44: { url: "/images/art-44.jpg", alt: "Лада: как АвтоВАЗ пережил эпохи", credit: "Throwawayacc222, CC0 (Wikimedia Commons)" },
    45: { url: "/images/art-45.jpg", alt: "Audi: четыре кольца и легенда quattro", credit: "M 93, CC BY-SA 3.0 de (Wikimedia Commons)" },
    46: { url: "/images/art-46.jpg", alt: "Утильсбор 2026: как меняются цены на новые авто", credit: "Roger Cornfoot , CC BY-SA 2.0 (Wikimedia Commons)" },
    47: { url: "/images/art-47.jpg", alt: "Китайские электрокары захватывают Европу", credit: "Navigator84, CC BY-SA 4.0 (Wikimedia Commons)" },
    48: { url: "/images/art-48.jpg", alt: "Беспилотные такси: где они уже возят пассажиров", credit: "Grendelkhan, CC BY-SA 4.0 (Wikimedia Commons)" },
    49: { url: "/images/art-49.jpg", alt: "Водород против батареи: второй шанс H2-технологий", credit: "Matti Blume, CC BY-SA 4.0 (Wikimedia Commons)" },
    50: { url: "/images/art-50.jpg", alt: "Куда уходит вторичный рынок: тренды Б/у автомобилей", credit: "Thomas R Machnitzki, CC BY 3.0 (Wikimedia Commons)" },
    51: { url: "/images/art-51.jpg", alt: "Домашняя зарядка: ставим зарядную станцию без лишних трат", credit: "Mariordo (Mario Roberto Durán Ortiz), CC BY-SA 4.0 (Wikimedia Commons)" },
    52: { url: "/images/art-52.jpg", alt: "Chevrolet: как Америка строила свои легенды", credit: "Berthold Werner, CC BY-SA 3.0 (Wikimedia Commons)" },
    53: { url: "/images/art-53.jpg", alt: "Лада Vesta 2026: что изменилось в главной модели АвтоВАЗа", credit: "Dmitry Racer, CC BY-SA 4.0 (Wikimedia Commons)" },
    54: { url: "/images/art-54.jpg", alt: "УАЗ «Патриот» и внедорожники: что нового в 2026", credit: "Dogs.barking.duster.rolling, CC BY-SA 4.0 (Wikimedia Commons)" },
    55: { url: "/images/art-55.jpg", alt: "АвтоВАЗ 2026: новые модели и планы концерна", credit: "Valera N. Ttrubin, CC BY-SA 3.0 (Wikimedia Commons)" },
    56: { url: "/images/art-56.jpg", alt: "Москвич и возрождение российских автобрендов", credit: "С. А. И., CC BY-SA 4.0 (Wikimedia Commons)" },
    57: { url: "/images/art-57.jpg", alt: "Локализация в России: что собирают на автозаводах", credit: "Albert duce, CC BY-SA 3.0 (Wikimedia Commons)" },
    58: { url: "/images/art-58.jpg", alt: "Льготы и субсидии: как выгодно купить российский автомобиль", credit: "chen chin (ducktail964) from taipei, taiwan, CC BY 2.0 (Wikimedia Commons)" },
    59: { url: "/images/art-59.jpg", alt: "Рынок новых автомобилей в России: итоги полугодия 2026", credit: "Stacey Harris , CC BY-SA 2.0 (Wikimedia Commons)" },
    60: { url: "/images/art-60.jpg", alt: "Почему дорожают автомобили: факторы цен 2026", credit: "Stacey Harris , CC BY-SA 2.0 (Wikimedia Commons)" },
    61: { url: "/images/art-61.jpg", alt: "Параллельный импорт автомобилей: что осталось от серых схем", credit: "DmitTrix, CC BY 4.0 (Wikimedia Commons)" },
    62: { url: "/images/art-62.jpg", alt: "Рейтинг марок по продажам в России 2026", credit: "Paul Harrop, CC BY-SA 2.0 (Wikimedia Commons)" },
    63: { url: "/images/art-63.jpg", alt: "Дилеры уходят в онлайн: как теперь покупают автомобили", credit: "Thomas Nugent, CC BY-SA 2.0 (Wikimedia Commons)" },
    64: { url: "/images/art-64.jpg", alt: "ОСАГО и каско для новых автомобилей: что изменилось", credit: "Jiří Sedláček, CC BY-SA 4.0 (Wikimedia Commons)" },
    65: { url: "/images/art-65.jpg", alt: "«Атом»: российский электромобиль выходит на дороги", credit: "Stolbovsky, CC BY-SA 4.0 (Wikimedia Commons)" },
    66: { url: "/images/art-66.jpg", alt: "Российский авторынок в июле 2026: рост, лидеры и доля китайцев", credit: "Eric Jones, CC BY-SA 2.0 (Wikimedia Commons)" },
    67: { url: "/images/art-67.jpg", alt: "Euro 7: новые экологические нормы для автомобилей", credit: "Ruben de Rijcke, CC BY-SA 3.0 (Wikimedia Commons)" },
    68: { url: "/images/nissan-gtr.jpg", alt: "Nissan GT-R (R35)", credit: "Фото: Dinkun Chen, CC BY-SA 4.0 (Wikimedia Commons)" },
    69: { url: "/images/art-69.jpg", alt: "Дорога в дальнюю поездку", credit: "Фото: Ludovic Gibert, CC BY-SA 3.0 (Wikimedia Commons)" },
    70: { url: "/images/art-70.jpg", alt: "Kia EV3 электрокроссовер", credit: "Пресс-служба Kia" },
    71: { url: "/images/art-71.jpg", alt: "Комплектации Kia EV3", credit: "Пресс-служба Kia" },
    72: { url: "/images/art-72.jpg", alt: "Avore EX2S электромотоцикл", credit: "Официальный фотобанк" },
    73: { url: "/images/art-73.jpg", alt: "Зарядная станция электромобиля", credit: "Unsplash" },
    74: { url: "/images/art-74.jpg", alt: "Завод Tesla в Европе", credit: "Unsplash" },
    75: { url: "/images/art-75.jpg", alt: "Обновленный Haval H3", credit: "Пресс-служба Haval" },
    76: { url: "/images/art-76.jpg", alt: "Mercedes-AMG Black Series V8", credit: "Пресс-служба Mercedes-Benz" }
};

// ЧПУ-адреса статей (транслитерация заголовка). Ключ — номер статьи (1-based).
// При добавлении новой статьи добавляйте и слаг (или сгенерируйте его транслитерацией заголовка).
const SLUGS = {
    1: "elektromobili-v-2026-godu-gonka-za-zapasom-khoda-v-1000-km",
    2: "premery-goda-glavnye-avto-kotorye-vyydut-na-rynok",
    3: "toyota-put-ot-tkatskogo-stanka-do-mirovogo-lidera",
    4: "benzin-dizel-gibrid-ili-elektro-chto-vybrat-v-2026",
    5: "avtoprom-budushchego-bespilotniki-karshering-i-novye-rynki",
    6: "zaryadnye-stantsii-gde-zaryazhatsya-v-doroge-i-skolko-eto-stoit",
    7: "krossovery-2026-chto-vybirayut-semi",
    8: "turbo-ili-atmosfernik-chto-nadezhnee-na-samom-dele",
    9: "ferrari-kak-malenkaya-masterskaya-stala-simvolom-skorosti",
    10: "tesla-vs-kitayskie-brendy-kto-lidiruet-v-elektromobilyakh",
    11: "ekologicheskie-normy-kak-avtoprom-gotovitsya-k-zapretu-dvs",
    12: "volkswagen-narodnyy-avtomobil-i-ego-nasledie",
    13: "gibridy-protiv-elektrichestva-schitaem-chto-vygodnee",
    14: "dizel-zhiv-chto-proiskhodit-s-dizelnymi-motorami",
    15: "batarei-budushchego-natriy-tverdyy-elektrolit-i-lfp",
    16: "porsche-911-60-let-odnoy-legende",
    17: "kitayskie-brendy-shturmuyut-rynok-haval-exeed-i-geely-v-liderakh",
    18: "gibridy-2026-bolshe-ne-perekhodnyy-etap-a-samostoyatelnyy-klass",
    19: "bystraya-zaryadka-vazhnee-zapasa-khoda-epokha-800v-i-900v",
    20: "tverdotelnye-batarei-prototip-mercedes-proekhal-1205-km",
    21: "li-auto-elektronnoe-shassi-i-zapas-khoda-do-1650-km",
    22: "nadezhnost-kitayskikh-mashin-pochemu-servisy-zagruzheny-na-51",
    23: "reyting-prodazh-v-kitae-geely-ex2-xiaomi-su7-i-gonka-byd",
    24: "esteo-v27-gibrid-na-456-l-s-za-5-75-mln-rubley",
    25: "zeekr-bmw-i-gonka-za-900-voltovye-platformy",
    26: "changan-cs75-plus-awd-lokalizatsiya-i-polnyy-privod",
    27: "xiaomi-su7-kak-telefonnyy-gigant-vorvalsya-v-avtoprom",
    28: "elektromobil-zimoy-teryaem-li-my-zapas-khoda-v-moroz",
    29: "lfp-protiv-troynogo-litiya-kakaya-batareya-zhivet-dolshe",
    30: "rezhim-odnoy-pedali-chto-takoe-rekuperatsiya-i-kak-ey-polzovatsya",
    31: "b-u-elektromobil-na-chto-smotret-pri-pokupke",
    32: "sportkary-2026-elektricheskie-i-gibridnye-bestsellery",
    33: "miniveny-i-semeynye-krossovery-obzor-dlya-bolshikh-semey",
    34: "byudzhetnye-avto-2026-chto-kupit-do-2-mln-rubley",
    35: "pikapy-nastupayut-pochemu-gruzovye-mashiny-stanovyatsya-modnymi",
    36: "remen-grm-protiv-tsepi-chto-nadezhnee-i-chto-deshevle",
    37: "kakoe-maslo-lit-v-dvigatel-i-kogda-menyat",
    38: "variator-ili-akpp-sravnivaem-korobki-peredach",
    39: "kak-ekonomit-toplivo-10-privychek-voditelya",
    40: "robot-protiv-avtomata-gde-podvokh-v-robotakh",
    41: "bmw-ot-aviatsionnykh-dvigateley-do-troyki",
    42: "mercedes-benz-rozhdenie-trekhluchevoy-zvezdy",
    43: "honda-ot-mopedov-do-legendarnogo-nsx",
    44: "lada-kak-avtovaz-perezhil-epokhi",
    45: "audi-chetyre-koltsa-i-legenda-quattro",
    46: "utilsbor-2026-kak-menyayutsya-tseny-na-novye-avto",
    47: "kitayskie-elektrokary-zakhvatyvayut-evropu",
    48: "bespilotnye-taksi-gde-oni-uzhe-vozyat-passazhirov",
    49: "vodorod-protiv-batarei-vtoroy-shans-h2-tekhnologiy",
    50: "kuda-ukhodit-vtorichnyy-rynok-trendy-b-u-avtomobiley",
    51: "domashnyaya-zaryadka-stavim-zaryadnuyu-stantsiyu-bez-lishnikh-trat",
    52: "chevrolet-kak-amerika-stroila-svoi-legendy",
    53: "lada-vesta-2026-chto-izmenilos-v-glavnoy-modeli-avtovaza",
    54: "uaz-patriot-i-vnedorozhniki-chto-novogo-v-2026",
    55: "avtovaz-2026-novye-modeli-i-plany-kontserna",
    56: "moskvich-i-vozrozhdenie-rossiyskikh-avtobrendov",
    57: "lokalizatsiya-v-rossii-chto-sobirayut-na-avtozavodakh",
    58: "lgoty-i-subsidii-kak-vygodno-kupit-rossiyskiy-avtomobil",
    59: "rynok-novykh-avtomobiley-v-rossii-itogi-polugodiya-2026",
    60: "pochemu-dorozhayut-avtomobili-faktory-tsen-2026",
    61: "parallelnyy-import-avtomobiley-chto-ostalos-ot-serykh-skhem",
    62: "reyting-marok-po-prodazham-v-rossii-2026",
    63: "dilery-ukhodyat-v-onlayn-kak-teper-pokupayut-avtomobili",
    64: "osago-i-kasko-dlya-novykh-avtomobiley-chto-izmenilos",
    65: "atom-rossiyskiy-elektromobil-vykhodit-na-dorogi",
    66: "rossiyskiy-avtorynok-v-iyule-2026-rost-lidery-i-dolya-kitaytsev",
    67: "euro-7-novye-ekologicheskie-normy-dlya-avtomobiley",
    68: "nissan-ot-datsun-do-mirovogo-lidera-i-obratno",
    69: "podgotovka-k-dalney-poezdke-chek-list-iz-10-punktov",
    70: "kia-ev3-dostupnyy-elektrokrossover-s-zapasom-khoda-do-516-km",
    71: "tseny-i-komplektatsii-kia-ev3-novyy-lider-v-dostupnom-segmente",
    72: "avore-ex2s-dostupnyy-elektromototsikl-so-skorostyu-do-115-km-h",
    73: "trevoga-zapasa-khoda-pochemu-strakh-pered-batareyami-ukhodit-v-proshloe",
    74: "tesla-i-profsoyuzy-v-evrope-zavershenie-zabastovki-v-shvetsii",
    75: "haval-h3"
,
    76: "novaya-chernaya-seriya-mercedes-budet-ispol-zovat-dikiy-ploskiy-v8"
,
    77: "khotite-unikal-nyy-cayenne-ili-panamera-porsche-sdelaet-eto-vozmozhnym"
,
    78: "spyker-vozvrashchaetsya-debyut-c8-preliator-xxv-moshchnost-yu-789-l-s"
,
    79: "gordon-murray-s1-sovremennyy-mclaren-f1-kotorogo-my-zhdali"
,
    80: "pokupateli-911-gt3-pomogli-ubedit-porsche-dat-carrera-s-rukovodstvo"

};

if (typeof module !== 'undefined' && module.exports) module.exports = { IMAGES, SLUGS };
