// Фото статей: url, alt, credit (Wikimedia Commons, свободные лицензии CC BY-SA/CC0).
// Файл загружается и на главной (превью в карточках), и доступен в Node (generate_articles.js).
const IMAGES = {
    1: { url: "/images/art-01.jpg", alt: "Электромобили в 2026 году: гонка за запасом хода в 1000 км", credit: "CEphoto, Uwe Aranas, CC BY-SA 3.0 (Wikimedia Commons)" },
    2: { url: "/images/art-02.jpg", alt: "Премьеры года: главные авто, которые выйдут на рынок", credit: "D. Benjamin Miller, CC0 (Wikimedia Commons)" },
    3: { url: "/images/art-03.jpg", alt: "Toyota: путь от ткацкого станка до мирового лидера", credit: "Petar Milošević, CC BY-SA 4.0 (Wikimedia Commons)" },
    4: { url: "/images/art-04.jpg", alt: "Бензин, дизель, гибрид или электро: что выбрать в 2026?", credit: "Ferdinand Reus, CC BY-SA 2.0 (Wikimedia Commons)" },
    5: { url: "/images/art-05.jpg", alt: "Автопром будущего: беспилотники, каршеринг и новые рынки", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    6: { url: "/images/art-06.jpg", alt: "Зарядные станции: где заряжаться в дороге и сколько это стоит", credit: "Julian Herzog (Website), CC BY 4.0 (Wikimedia Commons)" },
    7: { url: "/images/art-07.jpg", alt: "Кроссоверы 2026: что выбирают семьи", credit: "Corvettec6r, CC0 (Wikimedia Commons)" },
    8: { url: "/images/art-08.jpg", alt: "Турбо или атмосферник: что надёжнее на самом деле", credit: "Quentin Schwinn (NASA), Public domain (Wikimedia Commons)" },
    9: { url: "/images/ferrari.jpg", alt: "Ferrari 250 GTO — легендарная модель марки", credit: "Фото: Lothar Spurzem, CC BY-SA 2.0 (Wikimedia Commons)" },
    10: { url: "/images/art-10.jpg", alt: "Tesla vs китайские бренды: кто лидирует в электромобилях", credit: "Alexander-93, CC BY-SA 4.0 (Wikimedia Commons)" },
    11: { url: "/images/art-11.jpg", alt: "Экологические нормы: как автопром готовится к запрету ДВС", credit: "Ruben de Rijcke, CC BY-SA 3.0 (Wikimedia Commons)" },
    12: { url: "/images/art-12.jpg", alt: "Volkswagen: «народный автомобиль» и его наследие", credit: "Dllu, CC BY-SA 4.0 (Wikimedia Commons)" },
    13: { url: "/images/art-13.jpg", alt: "Гибриды против электричества: считаем, что выгоднее", credit: "Alexander-93, CC BY-SA 4.0 (Wikimedia Commons)" },
    14: { url: "/images/art-14.jpg", alt: "Дизель жив? Что происходит с дизельными моторами", credit: "Lemon3 at German Wikipedia, CC BY-SA 3.0 (Wikimedia Commons)" },
    15: { url: "/images/art-15.jpg", alt: "Батареи будущего: натрий, твёрдый электролит и LFP", credit: "Raimond Spekking, CC BY-SA 4.0 (Wikimedia Commons)" },
    16: { url: "/images/porsche-911.jpg", alt: "Porsche 911 GT3 (992)", credit: "Фото: Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    17: { url: "/images/art-17.jpg", alt: "Китайские бренды штурмуют рынок: HAVAL, EXEED и Geely в лидерах", credit: "Jengtingchen, CC BY-SA 4.0 (Wikimedia Commons)" },
    18: { url: "/images/art-18.jpg", alt: "Гибриды 2026: больше не «переходный этап», а самостоятельный класс", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    19: { url: "/images/art-19.jpg", alt: "Быстрая зарядка важнее запаса хода: эпоха 800V и 900V", credit: "original: Michael Movchinedited by Felix Müller, CC BY-SA 3.0 (Wikimedia Commons)" },
    20: { url: "/images/art-20.jpg", alt: "Твёрдотельные батареи: прототип Mercedes проехал 1205 км", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    21: { url: "/images/art-21.jpg", alt: "Li Auto: электронное шасси и запас хода до 1650 км", credit: "Evnerd, CC BY-SA 4.0 (Wikimedia Commons)" },
    22: { url: "/images/art-22.jpg", alt: "Надёжность китайских машин: почему сервисы загружены на 51%", credit: "Alexander-93, CC BY-SA 4.0 (Wikimedia Commons)" },
    23: { url: "/images/art-23.jpg", alt: "Рейтинг продаж в Китае: Geely EX2, Xiaomi SU7 и гонка BYD", credit: "John kwame westafrica, CC0 (Wikimedia Commons)" },
    24: { url: "/images/art-24.jpg", alt: "ESTEO V27: гибрид на 456 л.с. за 5,75 млн рублей", credit: "JustAnotherCarDesigner, CC BY-SA 4.0 (Wikimedia Commons)" },
    25: { url: "/images/art-25.jpg", alt: "Zeekr, BMW и гонка за 900-вольтовые платформы", credit: "Alexander Migl, CC BY-SA 4.0 (Wikimedia Commons)" },
    26: { url: "/images/art-26.jpg", alt: "Changan CS75 Plus AWD: локализация и полный привод", credit: "Jengtingchen, CC BY-SA 4.0 (Wikimedia Commons)" },
    27: { url: "/images/art-27.jpg", alt: "Xiaomi SU7: как телефонный гигант ворвался в автопром", credit: "Zoerides, CC0 (Wikimedia Commons)" },
    28: { url: "/images/art-28.jpg", alt: "Электромобиль зимой: теряем ли мы запас хода в мороз", credit: "John S Turner, CC BY-SA 2.0 (Wikimedia Commons)" },
    29: { url: "/images/art-29.jpg", alt: "LFP против тройного лития: какая батарея живёт дольше", credit: "Krzysztof Woźnica - KyloDee, Public domain (Wikimedia Commons)" },
    30: { url: "/images/art-30.jpg", alt: "Режим одной педали: что такое рекуперация и как ей пользоваться", credit: "Keanu4, CC BY-SA 3.0 (Wikimedia Commons)" },
    31: { url: "/images/art-31.jpg", alt: "Б/у электромобиль: на что смотреть при покупке", credit: " Dmitry Ivanov.., CC BY-SA 4.0 (Wikimedia Commons)" },
    32: { url: "/images/art-32.jpg", alt: "Спорткары 2026: электрические и гибридные бестселлеры", credit: "Matti Blume, CC BY-SA 4.0 (Wikimedia Commons)" },
    33: { url: "/images/art-33.jpg", alt: "Минивэны и семейные кроссоверы: обзор для больших семей", credit: "IFCAR, Public domain (Wikimedia Commons)" },
    34: { url: "/images/art-34.jpg", alt: "Бюджетные авто 2026: что купить до 2 млн рублей", credit: "JanekJankowski, CC BY-SA 4.0 (Wikimedia Commons)" },
    35: { url: "/images/art-35.jpg", alt: "Пикапы наступают: почему грузовые машины становятся модными", credit: "Sylvainbrousseau, CC BY-SA 3.0 (Wikimedia Commons)" },
    36: { url: "/images/art-36.jpg", alt: "Ремень ГРМ против цепи: что надёжнее и что дешевле", credit: "Criveros0248, CC BY-SA 3.0 (Wikimedia Commons)" },
    37: { url: "/images/art-37.jpg", alt: "Какое масло лить в двигатель и когда менять", credit: "Pittigrilli, CC0 (Wikimedia Commons)" },
    38: { url: "/images/art-38.jpg", alt: "Вариатор или АКПП: сравниваем коробки передач", credit: "Hoikka1, CC BY-SA 3.0 (Wikimedia Commons)" },
    39: { url: "/images/art-39.jpg", alt: "Как экономить топливо: 10 привычек водителя", credit: "Sonett72 at English Wikipedia, Public domain (Wikimedia Commons)" },
    40: { url: "/images/art-40.jpg", alt: "Робот против автомата: где подвох в «роботах»", credit: "Robbie Sproule from Montreal, Canada, CC BY 2.0 (Wikimedia Commons)" },
    41: { url: "/images/art-41.jpg", alt: "BMW: от авиационных двигателей до «тройки»", credit: "Jeroen Coebergh, CC0 (Wikimedia Commons)" },
    42: { url: "/images/art-42.jpg", alt: "Mercedes-Benz: рождение трёхлучевой звезды", credit: "Dietmar Rabich, CC BY-SA 4.0 (Wikimedia Commons)" },
    43: { url: "/images/art-43.jpg", alt: "Honda: от мопедов до легендарного NSX", credit: "ed g2s • talk, CC BY-SA 3.0 (Wikimedia Commons)" },
    44: { url: "/images/art-44.jpg", alt: "Лада: как АвтоВАЗ пережил эпохи", credit: "Throwawayacc222, CC0 (Wikimedia Commons)" },
    45: { url: "/images/art-45.jpg", alt: "Audi: четыре кольца и легенда quattro", credit: "M 93, CC BY-SA 3.0 de (Wikimedia Commons)" },
    46: { url: "/images/art-46.jpg", alt: "Утильсбор 2026: как меняются цены на новые авто", credit: "Roger Cornfoot , CC BY-SA 2.0 (Wikimedia Commons)" },
    47: { url: "/images/art-47.jpg", alt: "Китайские электрокары захватывают Европу", credit: "Navigator84, CC BY-SA 4.0 (Wikimedia Commons)" },
    48: { url: "/images/art-48.jpg", alt: "Беспилотные такси: где они уже возят пассажиров", credit: "Grendelkhan, CC BY-SA 4.0 (Wikimedia Commons)" },
    49: { url: "/images/art-49.jpg", alt: "Водород против батареи: второй шанс H2-технологий", credit: "Matti Blume, CC BY-SA 4.0 (Wikimedia Commons)" },
    50: { url: "/images/art-50.jpg", alt: "Куда уходит вторичный рынок: тренды Б/у автомобилей", credit: "Thomas R Machnitzki, CC BY 3.0 (Wikimedia Commons)" },
    51: { url: "/images/art-51.jpg", alt: "Домашняя зарядка: ставим зарядную станцию без лишних трат", credit: "Mariordo (Mario Roberto Durán Ortiz), CC BY-SA 4.0 (Wikimedia Commons)" },
    52: { url: "/images/art-52.jpg", alt: "Chevrolet: как Америка строила свои легенды", credit: "Berthold Werner, CC BY-SA 3.0 (Wikimedia Commons)" },
    53: { url: "/images/art-53.jpg", alt: "Лада Vesta 2026: что изменилось в главной модели АвтоВАЗа", credit: "Dmitry Racer, CC BY-SA 4.0 (Wikimedia Commons)" },
    54: { url: "/images/art-54.jpg", alt: "УАЗ «Патриот» и внедорожники: что нового в 2026", credit: "Dogs.barking.duster.rolling, CC BY-SA 4.0 (Wikimedia Commons)" },
    55: { url: "/images/art-55.jpg", alt: "АвтоВАЗ 2026: новые модели и планы концерна", credit: "Valera N. Ttrubin, CC BY-SA 3.0 (Wikimedia Commons)" },
    56: { url: "/images/art-56.jpg", alt: "Москвич и возрождение российских автобрендов", credit: "С. А. И., CC BY-SA 4.0 (Wikimedia Commons)" },
    57: { url: "/images/art-57.jpg", alt: "Локализация в России: что собирают на автозаводах", credit: "Albert duce, CC BY-SA 3.0 (Wikimedia Commons)" },
    58: { url: "/images/art-58.jpg", alt: "Льготы и субсидии: как выгодно купить российский автомобиль", credit: "chen chin (ducktail964) from taipei, taiwan, CC BY 2.0 (Wikimedia Commons)" },
    59: { url: "/images/art-59.jpg", alt: "Рынок новых автомобилей в России: итоги полугодия 2026", credit: "Stacey Harris , CC BY-SA 2.0 (Wikimedia Commons)" },
    60: { url: "/images/art-60.jpg", alt: "Почему дорожают автомобили: факторы цен 2026", credit: "Stacey Harris , CC BY-SA 2.0 (Wikimedia Commons)" },
    61: { url: "/images/art-61.jpg", alt: "Параллельный импорт автомобилей: что осталось от серых схем", credit: "DmitTrix, CC BY 4.0 (Wikimedia Commons)" },
    62: { url: "/images/art-62.jpg", alt: "Рейтинг марок по продажам в России 2026", credit: "Paul Harrop, CC BY-SA 2.0 (Wikimedia Commons)" },
    63: { url: "/images/art-63.jpg", alt: "Дилеры уходят в онлайн: как теперь покупают автомобили", credit: "Thomas Nugent, CC BY-SA 2.0 (Wikimedia Commons)" },
    64: { url: "/images/art-64.jpg", alt: "ОСАГО и каско для новых автомобилей: что изменилось", credit: "Jiří Sedláček, CC BY-SA 4.0 (Wikimedia Commons)" },
    65: { url: "/images/art-65.jpg", alt: "«Атом»: российский электромобиль выходит на дороги", credit: "Stolbovsky, CC BY-SA 4.0 (Wikimedia Commons)" },
    66: { url: "/images/art-66.jpg", alt: "Российский авторынок в июле 2026: рост, лидеры и доля китайцев", credit: "Eric Jones, CC BY-SA 2.0 (Wikimedia Commons)" },
    67: { url: "/images/art-67.jpg", alt: "Euro 7: новые экологические нормы для автомобилей", credit: "Ruben de Rijcke, CC BY-SA 3.0 (Wikimedia Commons)" },
    68: { url: "/images/nissan-gtr.jpg", alt: "Nissan GT-R (R35)", credit: "Фото: Dinkun Chen, CC BY-SA 4.0 (Wikimedia Commons)" }
};

if (typeof module !== 'undefined' && module.exports) module.exports = { IMAGES };
