// База характеристик автомобилей для интерактивного сравнения «бок о бок»
// Поддерживает работу на сайте и внутри Telegram Mini App
const CARS_DATABASE = [
    {
        id: 'lada-vesta',
        name: 'Лада Vesta NG (2026)',
        category: 'Седаны / Бюджетные',
        image: '/images/art-53.jpg',
        price: '1.5 – 1.9 млн ₽',
        engine: '1.8 EVO (Бензин)',
        power: 122, // л.с.
        powerUnit: 'л.с.',
        acceleration: 11.6, // 0-100 с (меньше = лучше)
        clearance: 178, // мм (больше = лучше)
        drive: 'Передний (FWD)',
        driveType: 'FWD',
        transmission: 'Вариатор (CVT)',
        trunk: 480, // л (больше = лучше)
        length: 4440,
        width: 1764,
        height: 1496,
        dimensions: '4440 × 1764 × 1496 мм',
        fuel: '7.3 л / 100 км',
        fuelVal: 7.3,
        fuelType: 'Бензин АИ-92/95'
    },
    {
        id: 'haval-jolion',
        name: 'Haval Jolion 4WD',
        category: 'Компактные кроссоверы',
        image: '/images/art-75.jpg',
        price: '2.4 – 2.8 млн ₽',
        engine: '1.5T Турбо',
        power: 150,
        powerUnit: 'л.с.',
        acceleration: 9.8,
        clearance: 190,
        drive: 'Полный (4WD)',
        driveType: 'AWD',
        transmission: 'Робот 7DCT',
        trunk: 330,
        length: 4472,
        width: 1841,
        height: 1574,
        dimensions: '4472 × 1841 × 1574 мм',
        fuel: '8.2 л / 100 км',
        fuelVal: 8.2,
        fuelType: 'Бензин АИ-95'
    },
    {
        id: 'geely-coolray',
        name: 'Geely Coolray New',
        category: 'Компактные кроссоверы',
        image: '/images/art-23.jpg',
        price: '2.5 – 2.9 млн ₽',
        engine: '1.5T 4-цилиндра',
        power: 147,
        powerUnit: 'л.с.',
        acceleration: 8.1,
        clearance: 180,
        drive: 'Передний (FWD)',
        driveType: 'FWD',
        transmission: 'Робот 7DCT',
        trunk: 330,
        length: 4380,
        width: 1810,
        height: 1615,
        dimensions: '4380 × 1810 × 1615 мм',
        fuel: '6.1 л / 100 км',
        fuelVal: 6.1,
        fuelType: 'Бензин АИ-95'
    },
    {
        id: 'changan-cs75',
        name: 'Changan CS75 Plus AWD',
        category: 'Среднеразмерные кроссоверы',
        image: '/images/art-26.jpg',
        price: '3.5 – 3.9 млн ₽',
        engine: '2.0T Турбо',
        power: 233,
        powerUnit: 'л.с.',
        acceleration: 8.4,
        clearance: 190,
        drive: 'Полный (AWD)',
        driveType: 'AWD',
        transmission: 'Автомат 8AT (Aisin)',
        trunk: 620,
        length: 4710,
        width: 1865,
        height: 1710,
        dimensions: '4710 × 1865 × 1710 мм',
        fuel: '8.8 л / 100 км',
        fuelVal: 8.8,
        fuelType: 'Бензин АИ-95'
    },
    {
        id: 'chery-tiggo-7',
        name: 'Chery Tiggo 7 Pro Max AWD',
        category: 'Среднеразмерные кроссоверы',
        image: '/images/art-17.jpg',
        price: '2.7 – 3.2 млн ₽',
        engine: '1.6T TGDI',
        power: 150,
        powerUnit: 'л.с.',
        acceleration: 9.7,
        clearance: 190,
        drive: 'Полный (AWD)',
        driveType: 'AWD',
        transmission: 'Робот 7DCT',
        trunk: 475,
        length: 4500,
        width: 1842,
        height: 1705,
        dimensions: '4500 × 1842 × 1705 мм',
        fuel: '7.7 л / 100 км',
        fuelVal: 7.7,
        fuelType: 'Бензин АИ-95'
    },
    {
        id: 'tank-300',
        name: 'Tank 300 4WD',
        category: 'Рамные внедорожники',
        image: '/images/art-54.jpg',
        price: '4.1 – 4.8 млн ₽',
        engine: '2.0T Бензин (Part-Time + Блокировки)',
        power: 220,
        powerUnit: 'л.с.',
        acceleration: 10.1,
        clearance: 224,
        drive: 'Полный (Part-Time 4WD)',
        driveType: 'AWD',
        transmission: 'Автомат 8AT (ZF)',
        trunk: 410,
        length: 4760,
        width: 1930,
        height: 1903,
        dimensions: '4760 × 1930 × 1903 мм',
        fuel: '10.7 л / 100 км',
        fuelVal: 10.7,
        fuelType: 'Бензин АИ-95'
    },
    {
        id: 'zeekr-001',
        name: 'Zeekr 001 4WD',
        category: 'Премиум электромобили',
        image: '/images/art-25.jpg',
        price: '5.8 – 7.5 млн ₽',
        engine: '2 электромотора (800V)',
        power: 544,
        powerUnit: 'л.с.',
        acceleration: 3.8,
        clearance: 174,
        drive: 'Полный (e-AWD)',
        driveType: 'AWD',
        transmission: 'Прямой редуктор',
        trunk: 2144,
        length: 4970,
        width: 1999,
        height: 1560,
        dimensions: '4970 × 1999 × 1560 мм',
        fuel: '705 км (Батарея 100 кВт·ч)',
        fuelVal: 0,
        fuelType: 'Электро'
    },
    {
        id: 'kia-ev3',
        name: 'Kia EV3 Long Range',
        category: 'Электрокроссоверы',
        image: '/images/art-70.jpg',
        price: '3.6 – 4.2 млн ₽',
        engine: 'Электромотор (Батарея 81.4 кВт·ч)',
        power: 204,
        powerUnit: 'л.с.',
        acceleration: 7.5,
        clearance: 165,
        drive: 'Передний (e-FWD)',
        driveType: 'FWD',
        transmission: 'Редуктор',
        trunk: 460,
        length: 4300,
        width: 1850,
        height: 1560,
        dimensions: '4300 × 1850 × 1560 мм',
        fuel: '516 км (WLTP)',
        fuelVal: 0,
        fuelType: 'Электро'
    },
    {
        id: 'esteo-v27',
        name: 'ESTEO V27 Hybrid',
        category: 'Премиум гибриды',
        image: '/images/art-24.jpg',
        price: '5.75 млн ₽',
        engine: 'Гибрид PHEV (Турбо + 2 Электромотора)',
        power: 456,
        powerUnit: 'л.с.',
        acceleration: 4.8,
        clearance: 205,
        drive: 'Полный (AWD)',
        driveType: 'AWD',
        transmission: 'Гибридная 3DHT',
        trunk: 580,
        length: 4980,
        width: 1980,
        height: 1780,
        dimensions: '4980 × 1980 × 1780 мм',
        fuel: '1200 км (Запас хода)',
        fuelVal: 2.1,
        fuelType: 'Гибрид PHEV'
    },
    {
        id: 'li-auto-l7',
        name: 'Li Auto L7 Max',
        category: 'Премиум гибриды',
        image: '/images/art-21.jpg',
        price: '6.5 – 7.8 млн ₽',
        engine: 'Последовательный гибрид (EREV)',
        power: 449,
        powerUnit: 'л.с.',
        acceleration: 5.3,
        clearance: 180,
        drive: 'Полный (e-AWD)',
        driveType: 'AWD',
        transmission: 'Пневмоподвеска / Редуктор',
        trunk: 495,
        length: 5050,
        width: 1995,
        height: 1750,
        dimensions: '5050 × 1995 × 1750 мм',
        fuel: '1315 км (Запас хода)',
        fuelVal: 1.8,
        fuelType: 'Гибрид EREV'
    },
    {
        id: 'xiaomi-su7',
        name: 'Xiaomi SU7 Max',
        category: 'Электроспорткары',
        image: '/images/art-27.jpg',
        price: '4.8 – 6.2 млн ₽',
        engine: 'HyperEngine V6s (2 электромотора)',
        power: 673,
        powerUnit: 'л.с.',
        acceleration: 2.78,
        clearance: 140,
        drive: 'Полный (AWD)',
        driveType: 'AWD',
        transmission: 'Прямой привод',
        trunk: 517,
        length: 4997,
        width: 1963,
        height: 1440,
        dimensions: '4997 × 1963 × 1440 мм',
        fuel: '800 км (CLTC)',
        fuelVal: 0,
        fuelType: 'Электро'
    },
    {
        id: 'moskvich-3',
        name: 'Москвич 3 (2026)',
        category: 'Городские кроссоверы',
        image: '/images/art-56.jpg',
        price: '1.7 – 2.1 млн ₽',
        engine: '1.5T Турбо',
        power: 136,
        powerUnit: 'л.с.',
        acceleration: 10.5,
        clearance: 170,
        drive: 'Передний (FWD)',
        driveType: 'FWD',
        transmission: 'Вариатор (CVT)',
        trunk: 520,
        length: 4410,
        width: 1800,
        height: 1660,
        dimensions: '4410 × 1800 × 1660 мм',
        fuel: '6.6 л / 100 км',
        fuelVal: 6.6,
        fuelType: 'Бензин АИ-92/95'
    },
    {
        id: 'exeed-rx',
        name: 'Exeed RX AWD',
        category: 'Премиум кроссоверы',
        image: '/images/art-17.jpg',
        price: '4.6 – 5.2 млн ₽',
        engine: '2.0 TGDI',
        power: 249,
        powerUnit: 'л.с.',
        acceleration: 7.6,
        clearance: 187,
        drive: 'Полный (AWD CDC-подвеска)',
        driveType: 'AWD',
        transmission: 'Автомат 8AT',
        trunk: 660,
        length: 4781,
        width: 1920,
        height: 1671,
        dimensions: '4781 × 1920 × 1671 мм',
        fuel: '8.5 л / 100 км',
        fuelVal: 8.5,
        fuelType: 'Бензин АИ-95'
    },
    {
        id: 'toyota-camry',
        name: 'Toyota Camry (XV80)',
        category: 'Бизнес-седаны',
        image: '/images/art-03.jpg',
        price: '4.2 – 5.0 млн ₽',
        engine: '2.5 Hybrid Dynamic Force',
        power: 228,
        powerUnit: 'л.с.',
        acceleration: 7.8,
        clearance: 155,
        drive: 'Передний (FWD)',
        driveType: 'FWD',
        transmission: 'Планетарный e-CVT',
        trunk: 524,
        length: 4920,
        width: 1840,
        height: 1445,
        dimensions: '4920 × 1840 × 1445 мм',
        fuel: '4.4 л / 100 км',
        fuelVal: 4.4,
        fuelType: 'Гибрид HEV'
    },
    {
        id: 'porsche-911',
        name: 'Porsche 911 GTS T-Hybrid',
        category: 'Спорткары',
        image: '/images/art-16.jpg',
        price: '22 – 28 млн ₽',
        engine: '3.6L Boxer-6 T-Hybrid',
        power: 541,
        powerUnit: 'л.с.',
        acceleration: 3.0,
        clearance: 110,
        drive: 'Задний (RWD)',
        driveType: 'RWD',
        transmission: 'Робот 8-ст. PDK',
        trunk: 132,
        length: 4553,
        width: 1852,
        height: 1300,
        dimensions: '4553 × 1852 × 1300 мм',
        fuel: '10.5 л / 100 км',
        fuelVal: 10.5,
        fuelType: 'Бензин АИ-98/100'
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CARS_DATABASE };
}
